In [63]:
import numpy as np # creating alias np for numpy

In [64]:
# numpy is for numerical calculation
# it stores data in grid (arrays)
np.array([1,2,3,4,5,76,7,3]) # 1D array

array([ 1,  2,  3,  4,  5, 76,  7,  3])

In [65]:
np.array([])

array([], dtype=float64)

In [66]:
np.array([[1,2,3,4],[1,12,3,4],[1,2,3,4],[34,543,65,56]])

array([[  1,   2,   3,   4],
       [  1,  12,   3,   4],
       [  1,   2,   3,   4],
       [ 34, 543,  65,  56]])

In [67]:
x = np.array([[1,2,3,4],[1,12,3,4]])

In [68]:
x

array([[ 1,  2,  3,  4],
       [ 1, 12,  3,  4]])

In [69]:
x[0]

array([1, 2, 3, 4])

In [70]:
x[1]

array([ 1, 12,  3,  4])

In [71]:
x[1,1] # single index value of row and col
# x[row,col]

12

In [72]:
x[0:1,1:3]

array([[2, 3]])

In [73]:
x = np.array([[1,2,3,4],[1,12,3,4],[1,2,3,4],[34,543,65,56]])

In [74]:
x

array([[  1,   2,   3,   4],
       [  1,  12,   3,   4],
       [  1,   2,   3,   4],
       [ 34, 543,  65,  56]])

In [75]:
x[1:3,1:3]

array([[12,  3],
       [ 2,  3]])

In [76]:
x.shape

(4, 4)

In [77]:
x.T # Transpose of the matrix

array([[  1,   1,   1,  34],
       [  2,  12,   2, 543],
       [  3,   3,   3,  65],
       [  4,   4,   4,  56]])

In [78]:
x = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [79]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [80]:
y = np.array([[1,2,3],[4,5,6],[7,8,90]])

In [81]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

In [82]:
x + y # adding every element of one 2D array to 2D array

array([[ 11,  22,  33],
       [ 44,  55,  66],
       [ 77,  88, 180]])

In [83]:
x - y # subtracting every element of one 2D array to 2D array

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72,  0]])

In [84]:
x == y # checking every element of one 2D array to 2D array

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [85]:
x * y # multiplying every element of one 2D array to 2D array

array([[  10,   40,   90],
       [ 160,  250,  360],
       [ 490,  640, 8100]])

In [86]:
x / y # dividing every element of one 2D array to 2D array

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10.,  1.]])

In [87]:
np.zeros((4,4)) # tuple as a argument (row,col)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
np.ones((4,4)) # tuple as a argument (row,col)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
np.full((4,4),5) # tuple as a argument (row,col)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [90]:
np.eye(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [92]:
np.random.random((3,3))

array([[0.54699533, 0.16206125, 0.41118971],
       [0.06915933, 0.74954694, 0.73756212],
       [0.11201045, 0.73077358, 0.93847281]])

In [93]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [94]:
np.empty_like(x)

array([[4603102115431364352, 4595006892246238488, 4601078955209749484],
       [4589647875693594352, 4604926538150308562, 4604818588478334127],
       [4592735623945431928, 4604757442831682852, 4606628231165089989]])

In [95]:
# indexing

In [96]:
x = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [97]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [99]:
x[[0,2,1],[1,2,0]] # view from same array

array([20, 90, 40])

In [100]:
np.array([x[0,1],x[2,2],x[1,0]]) # separate array

array([20, 90, 40])

In [101]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [106]:
x > 50 #create a array of true false

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [107]:
x[x > 50] # creates a array of all elements greater than 5

array([60, 70, 80, 90])

In [108]:
np.add(x,y) # x + y

array([[ 11,  22,  33],
       [ 44,  55,  66],
       [ 77,  88, 180]])

In [111]:
np.subtract(x,y) # x - y

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72,  0]])

In [112]:
np.multiply(x,y) # x * y

array([[  10,   40,   90],
       [ 160,  250,  360],
       [ 490,  640, 8100]])

In [113]:
np.divide(x,y) # x / y

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10.,  1.]])

In [114]:
np.sqrt(x) 

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [115]:
np.sqrt(y)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 9.48683298]])

In [116]:
np.mod(x,y)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [118]:
np.dot(x,y) # dot product

array([[ 300,  360, 2850],
       [ 660,  810, 5820],
       [1020, 1260, 8790]])

In [119]:
np.sum(x,axis=1)

array([ 60, 150, 240])

In [120]:
np.sum(x,axis=0)

array([120, 150, 180])

In [121]:
x

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [123]:
x=x[:2,:]

In [124]:
x

array([[10, 20, 30],
       [40, 50, 60]])

In [125]:
np.reshape(x,(3,2))

array([[10, 20],
       [30, 40],
       [50, 60]])

In [126]:
x = np.array([[1,2],[3,4]],dtype = np.int32)

In [127]:
x

array([[1, 2],
       [3, 4]], dtype=int32)

In [128]:
y = np.ones((3,3),dtype = np.int64)

In [129]:
y

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])